language: php
php:
- 5.5

env:
- BD=pgsql

before_install:
- sudo apt-get update -q
- sudo apt-get install ruby-full -y
- gem install sass
- chmod 777 install-dependencies.sh
install: ./install-dependencies.sh

before_script: true

script: 
- phpunit Test.php



notifications:
  email:
    - gabtmora23@hotmail.com
  irc: "irc.freenode.org#yourfavouriteroomfortravis"
