language: php
php:
- 5.5

env:
- BD=pgsql

before_install:
- sudo apt-get update -q


before_script: true

script: 
- phpunit Test



notifications:
  email:
    - gabtmora23@hotmail.com
  irc: "irc.freenode.org#yourfavouriteroomfortravis"
